SELECT TOP (1000) [Id]
      ,[FirstName]
      ,[LastName]
      ,[Email]
      ,[DateCreated]
      ,[IsDisabled]
      ,[LastLoginDate]
      ,[LastAccDisableDate]
      
  FROM [CCSDB].[Acct].[Users]